# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c797480b6e1fc3d1495766327d0343d8e978e3d6da5757895e6d434921297c044245bf9e100964bb60cae3aac26dff4975451fe02a804d63f281da638f515274

test:
  secret_key_base: 11579c358770ac6355202dc6eeebeca9fe55deb0819fd8bdb790014b265d8d4a11dc45254156523b20c8b27e5c315dcc175c32dd59916f4e0b94933cc23f62ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
